# Generated by Django 5.0.6 on 2026-06-19 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('tag', models.CharField(default='', max_length=60)),
                ('color', models.CharField(default='var(--moss)', max_length=40)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('list', models.CharField(choices=[('inbox', 'Inbox'), ('next', 'Próximas acciones'), ('waiting', 'En espera de'), ('meetings', 'Compromisos de reunión'), ('portfolio', 'Rol · Portafolio'), ('watch', 'Vigilancia / Algún día')], default='inbox', max_length=20)),
                ('meta', models.CharField(blank=True, default='', max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['done', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['done', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('progress', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krs', to='api.objective')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RhythmLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rhythm', models.CharField(max_length=40)),
                ('day', models.DateField()),
            ],
            options={
                'ordering': ['-day'],
                'unique_together': {('rhythm', 'day')},
            },
        ),
    ]
